from django.shortcuts import render

# TODO: 1. NEWEST PRODUCTS
# TODO: 2. MOST VIEWED PRODUCTS
# TODO: 3. TOP RATED PRODUCTS
# TODO: 4. RECOMMENDED PRODUCTS
# TODO: 5. BEST SELLER PRODUCTS
# TODO: 6. HOTTEST PRODUCTS
# TODO: 7. BY USER
# TODO: 8. BY GENDER
# TODO: 9. BY AGE
# TODO: 10. BY COUNTRY
# TODO: 11. REGISTERED USERS (WITH DELETE)
# TODO: 12. VISITED USERS (DAY, WEEK, MOTH)
